### ISSUE TITLE
issues with gitfs

### ISSUE THREAD

**Issue by chaaridev** [gromgit/homebrew-fuse#19]
I tried to install gitfs using `brew install gromgit/fuse/gitfs-mac`

but I get this error when I try to mount my git repo

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/gitfs", line 33, in <module>
    sys.exit(load_entry_point('gitfs==0.5.1', 'console_scripts', 'gitfs')())
  File "/opt/homebrew/Cellar/gitfs-mac/0.5.2/libexec/lib/python3.9/site-packages/gitfs/__init__.py", line 19, in mount
    from gitfs.mounter import start_fuse
  File "/opt/homebrew/Cellar/gitfs-mac/0.5.2/libexec/lib/python3.9/site-packages/gitfs/mounter.py", line 21, in <module>
    from pygit2 import Keypair, UserPass
  File "/opt/homebrew/Cellar/gitfs-mac/0.5.2/libexec/lib/python3.9/site-packages/pygit2/__init__.py", line 33, in <module>
    from .blame import Blame, BlameHunk
  File "/opt/homebrew/Cellar/gitfs-mac/0.5.2/libexec/lib/python3.9/site-packages/pygit2/blame.py", line 27, in <module>
    from .ffi import ffi, C
  File "/opt/homebrew/Cellar/gitfs-mac/0.5.2/libexec/lib/python3.9/site-packages/pygit2/ffi.py", line 27, in <module>
    from ._libgit2 import ffi, lib as C
ImportError: dlopen(/opt/homebrew/Cellar/gitfs-mac/0.5.2/libexec/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so, 2): Symbol not found: _ffi_prep_closure
  Referenced from: /opt/homebrew/Cellar/gitfs-mac/0.5.2/libexec/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so
  Expected in: flat namespace
 in /opt/homebrew/Cellar/gitfs-mac/0.5.2/libexec/lib/python3.9/site-packages/_cffi_backend.cpython-39-darwin.so
```
I have MacOS running on Big Sur Version 11.5.2
Apple M1 chip

**Comment by gromgit** [comment]
I've updated the `cffi` resource in the formula, as it seems to be somewhat old. Can you `brew reinstall gromgit/fuse/gitfs-mac` and try your mount again? Thanks much!
