### ISSUE TITLE
failed to install clone

### ISSUE THREAD

**Issue by jgte** [gromgit/homebrew-fuse#24]
```
 $ brew install gromgit/fuse/rclone-mac
==> Downloading https://github.com/rclone/rclone/archive/v1.55.1.tar.gz
Already downloaded: /Users/teixeira/Library/Caches/Homebrew/downloads/df5e41a3e4f03ff66874dd6439e8ae64b91aa69d093248862bdcaa3b8c774384--rclone-1.55.1.tar.gz
==> Installing rclone-mac from gromgit/fuse
==> go build -ldflags -s -X github.com/rclone/rclone/fs.Version=v1.55.1 -tags cmount
==> /usr/local/Cellar/rclone-mac/1.55.1/bin/rclone-mac genautocomplete bash rclone.bash
Last 15 lines from /Users/teixeira/Library/Logs/Homebrew/rclone-mac/02.rclone-mac:
	runtime/proc.go:6498 +0x123 fp=0xc00094fd10 sp=0xc00094fbd8 pc=0x4048c83
runtime.doInit(0x6653820)
	runtime/proc.go:6475 +0x71 fp=0xc00094fe48 sp=0xc00094fd10 pc=0x4048bd1
runtime.doInit(0x6637680)
	runtime/proc.go:6475 +0x71 fp=0xc00094ff80 sp=0xc00094fe48 pc=0x4048bd1
runtime.main()
	runtime/proc.go:238 +0x1e6 fp=0xc00094ffe0 sp=0xc00094ff80 pc=0x403b9c6
runtime.goexit()
	runtime/asm_amd64.s:1581 +0x1 fp=0xc00094ffe8 sp=0xc00094ffe0 pc=0x406d6a1

goroutine 34 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0002b6980)
	go.opencensus.io@v0.22.6/stats/view/worker.go:276 +0xb9
created by go.opencensus.io/stats/view.init.0
	go.opencensus.io@v0.22.6/stats/view/worker.go:34 +0x92

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/gromgit/homebrew-fuse/issues
```

```
$ cat /Users/teixeira/Library/Logs/Homebrew/rclone-mac/02.rclone-mac
2021-09-23 11:39:46 +0200

/usr/local/Cellar/rclone-mac/1.55.1/bin/rclone-mac
genautocomplete
bash
rclone.bash

fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff2033fc9e]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff2033fc9e
stack: frame={sp:0x7ffeefbfe968, fp:0x7ffeefbfe9b8} stack=[0x7ffeefb7fa08,0x7ffeefbfea70)
0x00007ffeefbfe868:  0x01007ffeefbfe888  0x0000000000000004 
0x00007ffeefbfe878:  0x000000000000001f  0x00007fff2033fc9e 
0x00007ffeefbfe888:  0x0b01dfacedebac1e  0x0000000000000001 
0x00007ffeefbfe898:  0x00000000040390b1 <runtime.throw+0x0000000000000071>  0x00007ffeefbfe938 
0x00007ffeefbfe8a8:  0x0000000005694127  0x00007ffeefbfe8f0 
0x00007ffeefbfe8b8:  0x0000000004039368 <runtime.fatalthrow.func1+0x0000000000000048>  0x00000000066f6780 
0x00007ffeefbfe8c8:  0x0000000000000001  0x0000000000000001 
0x00007ffeefbfe8d8:  0x00007ffeefbfe938  0x00000000040390b1 <runtime.throw+0x0000000000000071> 
0x00007ffeefbfe8e8:  0x00000000066f6780  0x00007ffeefbfe928 
0x00007ffeefbfe8f8:  0x00000000040392f0 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbfe908 
0x00007ffeefbfe908:  0x0000000004039320 <runtime.fatalthrow.func1+0x0000000000000000>  0x00000000066f6780 
0x00007ffeefbfe918:  0x00000000040390b1 <runtime.throw+0x0000000000000071>  0x00007ffeefbfe938 
0x00007ffeefbfe928:  0x00007ffeefbfe958  0x00000000040390b1 <runtime.throw+0x0000000000000071> 
0x00007ffeefbfe938:  0x00007ffeefbfe940  0x00000000040390e0 <runtime.throw.func1+0x0000000000000000> 
0x00007ffeefbfe948:  0x00000000056b4f55  0x000000000000002a 
0x00007ffeefbfe958:  0x00007ffeefbfe9a8  0x000000000404faf6 <runtime.sigpanic+0x0000000000000396> 
0x00007ffeefbfe968: <0x00000000056b4f55  0x00000000066f6780 
0x00007ffeefbfe978:  0x00007ffeefbfe9e8  0x0000000004029f86 <runtime.(*mheap).allocSpan+0x0000000000000546> 
0x00007ffeefbfe988:  0x000000000670fca8  0x0000000000000007 
0x00007ffeefbfe998:  0x000000c00094ffe0  0x000000c00094ffe8 
0x00007ffeefbfe9a8:  0x00007ffeefbfe9f0 !0x00007fff2033fc9e 
0x00007ffeefbfe9b8: >0x00007ffeefbfe9f0  0x0000000006630000 
0x00007ffeefbfe9c8:  0x0000000000000a69  0x000000000434f365 <golang.org/x/sys/unix.libc_umask_trampoline+0x0000000000000005> 
0x00007ffeefbfe9d8:  0x000000000406f55f <runtime.syscall+0x000000000000001f>  0x000000c00094f9d8 
0x00007ffeefbfe9e8:  0x00007ffeefbfea30  0x000000c00094f9a8 
0x00007ffeefbfe9f8:  0x000000000406d3b0 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000001 
0x00007ffeefbfea08:  0x0000000004013400 <runtime.mapclear+0x0000000000000020>  0x3400000000000020 
0x00007ffeefbfea18:  0x0000000000000000  0x000000000672bc60 
0x00007ffeefbfea28:  0x0000000000000680  0x000000c0000001a0 
0x00007ffeefbfea38:  0x000000000406b4c9 <runtime.systemstack+0x0000000000000049>  0x0000000000000004 
0x00007ffeefbfea48:  0x000000000595df08  0x00000000066f6780 
0x00007ffeefbfea58:  0x00007ffeefbfeaa0  0x000000000406b3c5 <runtime.mstart+0x0000000000000005> 
0x00007ffeefbfea68:  0x000000000406b37d <runtime.rt0_go+0x000000000000013d> 
runtime.throw({0x56b4f55, 0x66f6780})
	runtime/panic.go:1198 +0x71
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff2033fc9e
stack: frame={sp:0x7ffeefbfe968, fp:0x7ffeefbfe9b8} stack=[0x7ffeefb7fa08,0x7ffeefbfea70)
0x00007ffeefbfe868:  0x01007ffeefbfe888  0x0000000000000004 
0x00007ffeefbfe878:  0x000000000000001f  0x00007fff2033fc9e 
0x00007ffeefbfe888:  0x0b01dfacedebac1e  0x0000000000000001 
0x00007ffeefbfe898:  0x00000000040390b1 <runtime.throw+0x0000000000000071>  0x00007ffeefbfe938 
0x00007ffeefbfe8a8:  0x0000000005694127  0x00007ffeefbfe8f0 
0x00007ffeefbfe8b8:  0x0000000004039368 <runtime.fatalthrow.func1+0x0000000000000048>  0x00000000066f6780 
0x00007ffeefbfe8c8:  0x0000000000000001  0x0000000000000001 
0x00007ffeefbfe8d8:  0x00007ffeefbfe938  0x00000000040390b1 <runtime.throw+0x0000000000000071> 
0x00007ffeefbfe8e8:  0x00000000066f6780  0x00007ffeefbfe928 
0x00007ffeefbfe8f8:  0x00000000040392f0 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbfe908 
0x00007ffeefbfe908:  0x0000000004039320 <runtime.fatalthrow.func1+0x0000000000000000>  0x00000000066f6780 
0x00007ffeefbfe918:  0x00000000040390b1 <runtime.throw+0x0000000000000071>  0x00007ffeefbfe938 
0x00007ffeefbfe928:  0x00007ffeefbfe958  0x00000000040390b1 <runtime.throw+0x0000000000000071> 
0x00007ffeefbfe938:  0x00007ffeefbfe940  0x00000000040390e0 <runtime.throw.func1+0x0000000000000000> 
0x00007ffeefbfe948:  0x00000000056b4f55  0x000000000000002a 
0x00007ffeefbfe958:  0x00007ffeefbfe9a8  0x000000000404faf6 <runtime.sigpanic+0x0000000000000396> 
0x00007ffeefbfe968: <0x00000000056b4f55  0x00000000066f6780 
0x00007ffeefbfe978:  0x00007ffeefbfe9e8  0x0000000004029f86 <runtime.(*mheap).allocSpan+0x0000000000000546> 
0x00007ffeefbfe988:  0x000000000670fca8  0x0000000000000007 
0x00007ffeefbfe998:  0x000000c00094ffe0  0x000000c00094ffe8 
0x00007ffeefbfe9a8:  0x00007ffeefbfe9f0 !0x00007fff2033fc9e 
0x00007ffeefbfe9b8: >0x00007ffeefbfe9f0  0x0000000006630000 
0x00007ffeefbfe9c8:  0x0000000000000a69  0x000000000434f365 <golang.org/x/sys/unix.libc_umask_trampoline+0x0000000000000005> 
0x00007ffeefbfe9d8:  0x000000000406f55f <runtime.syscall+0x000000000000001f>  0x000000c00094f9d8 
0x00007ffeefbfe9e8:  0x00007ffeefbfea30  0x000000c00094f9a8 
0x00007ffeefbfe9f8:  0x000000000406d3b0 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000001 
0x00007ffeefbfea08:  0x0000000004013400 <runtime.mapclear+0x0000000000000020>  0x3400000000000020 
0x00007ffeefbfea18:  0x0000000000000000  0x000000000672bc60 
0x00007ffeefbfea28:  0x0000000000000680  0x000000c0000001a0 
0x00007ffeefbfea38:  0x000000000406b4c9 <runtime.systemstack+0x0000000000000049>  0x0000000000000004 
0x00007ffeefbfea48:  0x000000000595df08  0x00000000066f6780 
0x00007ffeefbfea58:  0x00007ffeefbfeaa0  0x000000000406b3c5 <runtime.mstart+0x0000000000000005> 
0x00007ffeefbfea68:  0x000000000406b37d <runtime.rt0_go+0x000000000000013d> 
runtime.sigpanic()
	runtime/signal_unix.go:719 +0x396

goroutine 1 [syscall, locked to thread]:
syscall.syscall(0x434f360, 0x0, 0x0, 0x0)
	runtime/sys_darwin.go:22 +0x3b fp=0xc00094f9d8 sp=0xc00094f9b8 pc=0x4069f7b
syscall.syscall(0x0, 0x56dae05, 0x56bc356, 0xc000472a00)
	<autogenerated>:1 +0x26 fp=0xc00094fa20 sp=0xc00094f9d8 pc=0x406fd66
golang.org/x/sys/unix.Umask(0xc000472a00)
	golang.org/x/sys@v0.0.0-20210313110737-8e9fff1a3a18/unix/zsyscall_darwin_amd64.go:2143 +0x34 fp=0xc00094fa50 sp=0xc00094fa20 pc=0x434ee74
github.com/rclone/rclone/vfs/vfsflags.platformFlags(0x5386180)
	github.com/rclone/rclone/vfs/vfsflags/vfsflags_unix.go:14 +0x55 fp=0xc00094fab0 sp=0xc00094fa50 pc=0x50bad75
github.com/rclone/rclone/vfs/vfsflags.AddFlags(0xc0002e8580)
	github.com/rclone/rclone/vfs/vfsflags/vfsflags.go:41 +0x4c9 fp=0xc00094fb10 sp=0xc00094fab0 pc=0x50bace9
github.com/rclone/rclone/cmd/mountlib.NewMountCommand({0x5657287, 0x5}, 0x0, 0x57364a0)
	github.com/rclone/rclone/cmd/mountlib/mount.go:520 +0x1fb fp=0xc00094fb80 sp=0xc00094fb10 pc=0x50bbbdb
github.com/rclone/rclone/cmd/cmount.init.0()
	github.com/rclone/rclone/cmd/cmount/mount.go:34 +0x51 fp=0xc00094fbd8 sp=0xc00094fb80 pc=0x50c58b1
runtime.doInit(0x6645660)
	runtime/proc.go:6498 +0x123 fp=0xc00094fd10 sp=0xc00094fbd8 pc=0x4048c83
runtime.doInit(0x6653820)
	runtime/proc.go:6475 +0x71 fp=0xc00094fe48 sp=0xc00094fd10 pc=0x4048bd1
runtime.doInit(0x6637680)
	runtime/proc.go:6475 +0x71 fp=0xc00094ff80 sp=0xc00094fe48 pc=0x4048bd1
runtime.main()
	runtime/proc.go:238 +0x1e6 fp=0xc00094ffe0 sp=0xc00094ff80 pc=0x403b9c6
runtime.goexit()
	runtime/asm_amd64.s:1581 +0x1 fp=0xc00094ffe8 sp=0xc00094ffe0 pc=0x406d6a1

goroutine 34 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0002b6980)
	go.opencensus.io@v0.22.6/stats/view/worker.go:276 +0xb9
created by go.opencensus.io/stats/view.init.0
	go.opencensus.io@v0.22.6/stats/view/worker.go:34 +0x92

HOMEBREW_VERSION: 3.2.13-50-g1f0ed9d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1f0ed9ddf68ae727a8a71281e91dc1b7da5c9493
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b7255e563a701ba940d22d6519d30d6dbcf70573
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.WqwtF7NDrB/org.macosforge.xquartz:0
HOMEBREW_EDITOR: /usr/bin/vi
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_NO_BOOTSNAP: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.33.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6-x86_64
CLT: 12.5.0.22.9
Xcode: 12.5.1
XQuartz: 2.7.11 => /opt/X11

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j12
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_PATH: /usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/fuse
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/11
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/go/bin:/usr/bin:/bin:/usr/sbin:/sbin
```
Any ideas?

**Comment by gromgit** [comment]
Hi @jgte ! Apologies for the long delay. I've updated the `rclone-mac` to the latest source release, but the generated bottles are currently broken for some unknown reason. Please `brew update`, then `brew install -s gromgit/fuse/rclone-mac` to build from source, while I figure out what went wrong with bottling.

**Comment by dnicolson** [comment]
There still appears to be a bottling issue, this error message is displayed when running the binary:
`exec: Failed to execute process: '/usr/local/opt/rclone-mac/libexec/rclone/rclone' the file could not be run by the operating system.`

**Comment by gromgit** [comment]
Sorry, I got sidetracked when trying to figure out the bottle problems. Bottom line, it may be a Homebrew bottling bug, but I'd like to see if anyone else can replicate it before filing an issue.

Please run the following commands and post the output here. Thanks much!
```
git -C $(brew --repo gromgit/fuse) pull
mkdir -p /tmp/rclone-mac
cd /tmp/rclone-mac
brew rm --force gromgit/fuse/rclone-mac
brew install --build-bottle gromgit/fuse/rclone-mac
brew bottle gromgit/fuse/rclone-mac
tar xvf rclone-mac--1.57.0.*.tar.gz
file $(brew --prefix)/bin/rclone-mac rclone-mac/1.57.0/bin/rclone-mac
```

**Comment by dnicolson** [comment]
```
Already up to date.
==> Downloading https://ghcr.io/v2/homebrew/core/go/manifests/1.18
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/go/blobs/sha256:dbbe797302016b0
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Downloading https://github.com/rclone/rclone/archive/v1.57.0.tar.gz
Already downloaded: /Users/dave/Library/Caches/Homebrew/downloads/d967be192207e10f10e5d0af98a04c3e31d17210ded806c0d1746392ca19bbf1--rclone-1.57.0.tar.gz
==> Installing rclone-mac from gromgit/fuse
==> Installing dependencies for gromgit/fuse/rclone-mac: go
==> Installing gromgit/fuse/rclone-mac dependency: go
==> Pouring go--1.18.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/go/1.18: 11,947 files, 592.6MB
==> Installing gromgit/fuse/rclone-mac
==> go build -ldflags -s -X github.com/rclone/rclone/fs.Version=v1.57.0 -tags cm
==> /usr/local/Cellar/rclone-mac/1.57.0/bin/rclone-mac genautocomplete bash rclo
==> /usr/local/Cellar/rclone-mac/1.57.0/bin/rclone-mac genautocomplete bash rclo
==> /usr/local/Cellar/rclone-mac/1.57.0/bin/rclone-mac genautocomplete zsh _rclo
==> /usr/local/Cellar/rclone-mac/1.57.0/bin/rclone-mac genautocomplete zsh _rclo
==> Not running 'post_install' as we're building a bottle
You can run it manually using:
  brew postinstall gromgit/fuse/rclone-mac
==> Caveats
The rclone binary has been installed as `rclone-mac`,
to avoid conflict with the core `rclone` formula.
If you need to use it as `rclone`, add the "rclone" directory
to your PATH like:
  PATH="/usr/local/opt/rclone-mac/libexec/rclone:$PATH"
==> Summary
🍺  /usr/local/Cellar/rclone-mac/1.57.0: 12 files, 55.3MB, built in 24 seconds
==> Running `brew cleanup rclone-mac`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Caveats
==> rclone-mac
The rclone binary has been installed as `rclone-mac`,
to avoid conflict with the core `rclone` formula.
If you need to use it as `rclone`, add the "rclone" directory
to your PATH like:
  PATH="/usr/local/opt/rclone-mac/libexec/rclone:$PATH"
==> Determining gromgit/fuse/rclone-mac bottle rebuild...
==> Bottling rclone-mac--1.57.0.monterey.bottle.1.tar.gz...
==> Detecting if rclone-mac--1.57.0.monterey.bottle.1.tar.gz is relocatable...
./rclone-mac--1.57.0.monterey.bottle.1.tar.gz
  bottle do
    rebuild 1
    sha256 cellar: :any_skip_relocation, monterey: "9b7b8b496810914ad2406b2172f79fd7bd86e5df5a437da9c659b48dc68690cb"
  end
x rclone-mac/1.57.0/
x rclone-mac/1.57.0/INSTALL_RECEIPT.json
x rclone-mac/1.57.0/notes.txt
x rclone-mac/1.57.0/bin/
x rclone-mac/1.57.0/.brew/
x rclone-mac/1.57.0/libexec/
x rclone-mac/1.57.0/etc/
x rclone-mac/1.57.0/README.md
x rclone-mac/1.57.0/COPYING
x rclone-mac/1.57.0/share/
x rclone-mac/1.57.0/share/man/
x rclone-mac/1.57.0/share/zsh/
x rclone-mac/1.57.0/share/zsh/site-functions/
x rclone-mac/1.57.0/share/zsh/site-functions/_rclone-mac
x rclone-mac/1.57.0/share/zsh/site-functions/_rclone
x rclone-mac/1.57.0/share/man/man1/
x rclone-mac/1.57.0/share/man/man1/rclone-mac.1
x rclone-mac/1.57.0/etc/bash_completion.d/
x rclone-mac/1.57.0/etc/bash_completion.d/rclone
x rclone-mac/1.57.0/etc/bash_completion.d/rclone-mac
x rclone-mac/1.57.0/libexec/rclone/
x rclone-mac/1.57.0/libexec/rclone/rclone
x rclone-mac/1.57.0/.brew/rclone-mac.rb
x rclone-mac/1.57.0/bin/rclone-mac
/usr/local/bin/rclone-mac:        Mach-O 64-bit executable x86_64
rclone-mac/1.57.0/bin/rclone-mac: Mach-O 64-bit executable x86_64
```

**Comment by gromgit** [comment]
That's weird. Just to be sure, what's the output of:
```
ls -lL $(brew --prefix)/bin/rclone-mac rclone-mac/1.57.0/bin/rclone-mac
```
?

**Comment by gromgit** [comment]
And are you running Homebrew on an Intel Mac, or an M1 Mac in Rosetta mode?

**Comment by dnicolson** [comment]
> That's weird. Just to be sure, what's the output of:
> 
> ```
> ls -lL $(brew --prefix)/bin/rclone-mac rclone-mac/1.57.0/bin/rclone-mac
> ```
> 
> ?

On an Intel Mac:
```
ls: rclone-mac/1.57.0/bin/rclone-mac: No such file or directory
-r-xr-xr-x  1 dave  wheel  49354880 Nov  1 16:45 /usr/local/bin/rclone-mac
```

**Comment by gromgit** [comment]
> ls: rclone-mac/1.57.0/bin/rclone-mac: No such file or directory
> -r-xr-xr-x  1 dave  wheel  49354880 Nov  1 16:45 /usr/local/bin/rclone-mac

Sorry, can you run the `ls` command again in `/tmp/rclone-mac`?

**Comment by dnicolson** [comment]
```
ls -lL /tmp/rclone-mac
total 35136
drwxr-xr-x  3 dave  wheel        96 Mar 20 17:00 rclone-mac
-rw-r--r--  1 dave  wheel  17044640 Mar 20 17:00 rclone-mac--1.57.0.monterey.bottle.1.tar.gz
```

**Comment by gromgit** [comment]
Sorry, I meant:
```
cd /tmp/rclone-mac
ls -lL $(brew --prefix)/bin/rclone-mac rclone-mac/1.57.0/bin/rclone-mac
```

**Comment by dnicolson** [comment]
```
cd /tmp/rclone-mac
ls -lL $(brew --prefix)/bin/rclone-mac rclone-mac/1.57.0/bin/rclone-mac
-r-xr-xr-x  1 dave  wheel  49354880 Nov  1 16:45 /usr/local/bin/rclone-mac
-r-xr-xr-x  1 dave  wheel  49354880 Nov  1 16:45 rclone-mac/1.57.0/bin/rclone-mac
```

**Comment by gromgit** [comment]
Interesting, the bottle build seems to have worked for you, but fails miserably for me:
```
$ file /usr/local/bin/rclone-mac rclone-mac/1.57.0/bin/rclone-mac 
/usr/local/bin/rclone-mac:        Mach-O 64-bit executable x86_64
rclone-mac/1.57.0/bin/rclone-mac: data
```
Will have to dig further, but for now, you can clean up and continue using `rclone-mac`:
```
brew postinstall rclone-mac
cd ~
rm -fr /tmp/rclone-mac
```
Apologies for the inconvenience.

**Comment by gromgit** [comment]
@jgte @dnicolson Good news, the bottling issue has been resolved to a macOS bug: https://github.com/Homebrew/brew/issues/13012#issuecomment-1073305666

I've rebottled and tested `rclone-mac` on all platforms after Mojave, and all seems well. Please `brew rm rclone-mac`, then `brew install rclone-mac` and let me know if you're still seeing problems. Thanks much!
